create table public.events (
  id uuid not null default gen_random_uuid (),
  title text not null,
  description text not null,
  category public.event_category not null,
  committee_name text not null,
  created_by uuid not null,
  start_date date not null,
  end_date date not null,
  registration_deadline date not null,
  event_start_time time without time zone not null,
  event_end_time time without time zone not null,
  min_team_size integer not null default 1,
  max_team_size integer not null default 4,
  allow_individual boolean not null default true,
  mode public.event_mode not null default 'offline'::event_mode,
  venue text null,
  first_prize numeric(10, 2) null default 0,
  second_prize numeric(10, 2) null default 0,
  third_prize numeric(10, 2) null default 0,
  entry_fee numeric(10, 2) not null default 0,
  is_free boolean not null default true,
  rules jsonb null default '[]'::jsonb,
  banner_url text null,
  problem_statement_url text null,
  status public.event_status not null default 'draft'::event_status,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  ppt_submission_deadline date null,
  teams_to_shortlist integer null default 5,
  meals jsonb null default '[]'::jsonb,
  constraint events_pkey primary key (id),
  constraint events_created_by_fkey foreign KEY (created_by) references users (id)
) TABLESPACE pg_default;